### ISSUE TITLE
use with modal bottom sheet on Flutter web (Andorid Chrome)

### ISSUE THREAD

**Issue by yingming25** [SchabanBo/qlevar_router#102]
Hi @SchabanBo ~
I use qlevar_router with [modal bottom sheet](https://github.com/jamesblasco/modal_bottom_sheet/tree/main/modal_bottom_sheet) on Flutter web.
when i show bottom sheet then i press android go back, can i use [back_button_interceptor](https://github.com/marcglasberg/back_button_interceptor) for intercept go back event?

I don't know how to catch go back event for show confirm dialog.

**Comment by SchabanBo** [comment]
Hi @yingming25,
you can use `canPop` method for catching back events. If this method returns true, the back action will be preformed, otherwise the action will be canceled.
See this [example](https://github.com/SchabanBo/qlevar_router/blob/ce339e9deeba6517a9095643d3aeb3dd4653381a/example/lib/routes/middleware_routes.dart#L61)

**Comment by yingming25** [comment]
@SchabanBo Thanks!
