### ISSUE TITLE
Navigation challenges

### ISSUE THREAD

**Issue by michael-woolsey** [SchabanBo/qlevar_router#42]
Hello again @SchabanBo,

I have a issue where I need my screen to refresh, but since it's already in the history stack it does not reload.  I've read https://github.com/SchabanBo/qlevar_router/issues/27 but I am having a hard time understanding how I should accomplish the following.

My navigation example:
1. /start
2. /test/results/:resultId - `QR.to('/test/results/111')` - ✔️ loads properly
3. /test/results/:resultId/stuff/:stuffId - `QR.to('/test/results/111/stuff/222')` - ✔️ loads properly
4. /test/results/:resultId/otherDetails/:otherDetailsId - `QR.to('/test/results/111/otherDetails/333')` - ✔️ loads properly
5. /test/results/:resultId/stuff/:stuffId - `QR.to('/test/results/111/stuff/999')` - ❌ doesn't build again

The problem is, on # 5 the `stuff` screen doesn't reload because it's already been loaded.

I need both pieces of information, the `111` and the `999` so that I can display the screen correctly but I also need it to rebuild the screen with these new parameters.

You suggest to use `QR.replace(path, withPath)` but in this example I'm not sure what values I should use.  Can you tell me what you would do in this case to get # 5 to re-load the screen?

Thank you,
Michael

**Comment by SchabanBo** [comment]
@michael-woolsey let's go one by one:

## 1

> Now if I had a real event, something like `Function(QRoute)? onNavigated` that was more reliable and less brittle than what I am doing, that would be fantastic.

You can use now `QR.observer.onNavigate`.

## 2

> Am I supposed to be able to go back through the stack the same way I went through it originally?

Actually, that was right.

the stack was in the steps as following
1. `HomePage`
2.  `HomePage`  - ` bacteria 111`
3.  `HomePage`  - ` bacteria 111` - `food 888`
4.  Here you are using `QR.to` which uses `PopUntilOrPush` so when you navigate to `bacteria 111` it poped to `bacteria  111` which makes the stack =>  `HomePage`  - ` bacteria 111`
5.  `HomePage`  - ` bacteria 111` - `food 888`

Now you go back from food to bacteria, and the stack will be  `HomePage`  - ` bacteria 111`.
Then you go back again and you got the home page

## 3


> * I get this error when attempting to do `replace('/food/888', '/bacteria/111')` - `_AssertionError ('package:qlevar_router/src/controllers/qrouter_controller.dart': Failed assertion: line 189 pos 12: 'index != -1': Path /food/888 was not found in the stack)`

Here I was not considering the param when replacing. It is now Fixed in V1.5.4

## 4

> 1. I would navigate forward randomly through the available screens it would eventually crash.  Sometimes it's quick for the error, other times it took a lot of navigating. But this is the error message:

As a key I was taking a random number between 1-1000 when you add too many pages there will be a chance to duplicate numbers. Fixed too in V1.5.4

## 5

> 2\. When I had navigated in quite a few screens, then I started going back the system would eventually throw an exception as well.  This exception was in the growable_array.dart file `throw IterableElementError.noElement();`.

in the history settings, there is an option to `allowDuplications`  `QR.history.allowDuplications` which default false. so when adding a path that already exists in history the old one will be deleted. This is why you could not go back in the same way you navigated. you need to set this setting to true to get what you expect.


I hope this will make sense now. I will leave this open if you have any other notes. otherwise you can close it

**Comment by michael-woolsey** [comment]
Seems to work great, thanks @SchabanBo!
