### ISSUE TITLE
Transition between Nested children was not appropriate

### ISSUE THREAD

**Issue by manish1238** [SchabanBo/qlevar_router#73]
Hi @SchabanBo , is there anyway we can remove the default transition that occurs between nested children when navigating from one to another. Because the transition is not looking good. I tried setting different transitions using pageType but nothing are looking good. So is there any way we can set it as normal transition that happens with default Flutter framework when navigating between BottomNavigation or SideNavigation? You can use the below project for checking the transition between bottom navigation

https://github.com/manish1238/qlevar_test

Thank you.

**Comment by SchabanBo** [comment]
Hi @manish1238,
So, after a lot of debugging and searching, this is happening because the flutter team has changed the default animation for the material page. See [this.](https://github.com/flutter/flutter/pull/82596).
I will fix this in the next release. Until then, you can fix this by warping the child with a material widget:
```dart
    QRoute.withChild(
      path: '/dashboard',
      name: dashboard,
      initRoute: '/first',
      builderChild: (router) => DashboardPage(router),
      children: [
        QRoute(
          path: '/first',
          name: tabs[0],
          builder: () => const Material(child:FirstPage()),
        ),
        QRoute(
          path: '/second',
          name: tabs[1],
          builder: () => const Material(child: SecondPage()),
        ),
      ],
    ),
```
